INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (1, 'root', 'root', 1, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (2, 'admin', 'admin', 5, '经理', 3, '2021-06-15 15:54:53');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (4, '1', '1', 2, '扫地大妈', 1, '2021-06-07 20:43:20');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (5, 'Joey', '123', 5, 'CEO', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (6, '张三', '123', 1, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (7, '李四', '123', 2, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (8, '王五', '123', 2, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (9, '赵六', '123', 1, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (10, '孙七', '123', 5, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (11, '言责', '123', 2, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (12, '于为', '123', 2, '普通人员', 0, '');
INSERT INTO `t_user` (`id`, `username`, `password`, `career`, `post`, `num`, `signInDate`) VALUES (13, 'test', '123', 1, '普通人员', 0, '');
